[package]
name = "sim-runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "sim_runtime"
path = "src/lib.rs"

[dependencies]
libloading = "0.7"
num-bigint = "0.4"
num-traits = "0.2"
rand = "0.8"
