on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true
      
      - name: Apply Patches
        run: |
          make patch-all
      
      - name: Initialize Submodules
        run: |
          git submodule update --init --recursive
      
      - name: Get Submodule Hashes
        id: submodule-hashes
        run: |
          echo "circt-hash=$(git rev-parse HEAD:3rd-party/circt)" >> $GITHUB_OUTPUT
          echo "verilator-hash=$(git rev-parse HEAD:3rd-party/verilator)" >> $GITHUB_OUTPUT
          echo "ramulator2-hash=$(git rev-parse HEAD:3rd-party/ramulator2)" >> $GITHUB_OUTPUT

      - name: Restore Build Cache
        id: cache-build
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.assassyn-venv
            ${{ github.workspace }}/3rd-party/verilator
            ${{ github.workspace }}/3rd-party/circt/frontends/PyCDE
            ${{ github.workspace }}/3rd-party/ramulator2/build
            ${{ github.workspace }}/tools/c-ramulator2-wrapper/build
          key: ${{ runner.os }}-build-cache-${{ hashFiles('Makefile') }}-${{ hashFiles('scripts/init/*.inc') }}-${{ hashFiles('scripts/init/patches/*.patch') }}-${{ hashFiles('python/requirements.txt') }}-circt-${{ steps.submodule-hashes.outputs.circt-hash }}-verilator-${{ steps.submodule-hashes.outputs.verilator-hash }}-ramulator2-${{ steps.submodule-hashes.outputs.ramulator2-hash }}
          restore-keys: |
            ${{ runner.os }}-build-cache-

      - name: Clean CMake Cache
        run: |
          find . -name "CMakeCache.txt" -delete
          find . -name "CMakeFiles" -type d -exec rm -rf {} + 2>/dev/null || true
      
      - name: Build All Components
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss, building all components"
          . setup.sh && make build-all
      
      - name: Run All Tests
        run: |
          . setup.sh && make test-all
      
     
